herctime/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
     path('', include("index.urls", namespace='index')),
     path('serbian/', include("serbian_ver.urls", namespace='index-serbian')),
     path('admin/', admin.site.urls),
]

index/urls.py
from django.urls import path

from . import views

app_name = 'index'
urlpatterns = [
    path("", views.index, name="index"),
    path("contact/", views.contact, name="contact"),
    path("romani/", views.romani, name="romani"),
    path("consultation/", views.consultation, name="consultation"),
    path("weaning_program/family_and_gambler", views.weaningProgram, name="family_and_gambler"),
    path("weaning_program/treatment_of_gamblers", views.treatmentGamblers, name="treatment_of_gamblers"),
    path("weaning_program/gambling_problem_scene", views.gamblingProblem, name="gambling_problem_scene"),
    path("weaning_program/gambling_addiction", views.gamblingAddiction, name="gambling_addiction"),
    path("weaning_program/pathological_gambling", views.pathologicalGambling, name="pathological_gambling"),
    path("weaning_program/dealing_with_gambling_problem", views.dealingGambling, name="dealing_with_gambling_problem"),
    path("dejan_stankovic", views.dejanStankovic, name="dejan_stankovic"),
    path("herctime/gallery", views.gallery, name="gallery"),
    path("herctime/about_us", views.aboutUs, name="about_us"),
    path("herctime/privacy_policy", views.privacyPolicy, name="privacy_policy"),
    path("video_education", views.videoEducation, name="video_education"),
    path("blog", views.blog, name="blog"),
    path("books/oprostajno_pismo", views.oprostajnoPismo, name="oprostajno_pismo"),
]

serbian_ver/urls.py
from django.urls import path

from . import views

app_name = 'index-serbian'

urlpatterns = [
    path("", views.index, name="index-sr"),
    path("contact/", views.contact, name="contact"),
    path("weaning_program/treatment_of_gamblers", views.treatmentGamblers, name="treatment_of_gamblers"),
    path("weaning_program/family_and_gambler", views.weaningProgram, name="family_and_gambler"),
    path("weaning_program/gambling_problem_scene", views.gamblingProblem, name="gambling_problem_scene"),
    path("weaning_program/gambling_addiction", views.gamblingAddiction, name="gambling_addiction"),
    path("weaning_program/pathological_gambling", views.pathologicalGambling, name="pathological_gambling"),
    path("weaning_program/dealing_with_gambling_problem", views.dealingGambling, name="dealing_with_gambling_problem"),
    
]

serbian_ver/models.py
from django.db import models

# Create your models here.

index/views.py
from django.shortcuts import render


from django.http import HttpResponse


# def index(request):
#     return HttpResponse("Hello, world. You're at the polls index.")


def index(request):
    
    
    context = {
        

    }
    
    return render(request, 'index/index.html', context)



def contact(request):
    
    
    context = {
        

    }
    
    return render(request, 'index/contact.html', context)


def consultation(request):
    
    
    context = {
        

    }
    
    return render(request, 'index/consultation.html', context)


def romani(request):
    
    
    context = {
        

    }
    
    return render(request, 'greensoks/greensoks_1.html', context)


def weaningProgram(request):
    
    
    context = {
        

    }
    
    return render(request, 'index/family_and_gambler.html', context)



def treatmentGamblers(request):
    
    
    context = {
        

    }
    
    return render(request, 'index/treatment_of_gamblers.html', context)


def gamblingProblem(request):
    
    
    context = {
        

    }
    
    return render(request, 'index/gambling_problem_scene.html', context)


def gamblingAddiction(request):
    
    
    context = {
        

    }
    
    return render(request, 'index/gambling_addiction.html', context)


def pathologicalGambling(request):
    
    
    context = {
        

    }
    
    return render(request, 'index/pathological_gambling.html', context)


def dealingGambling(request):
    
    
    context = {
        

    }
    
    return render(request, 'index/dealing_with_gambling_problem.html', context)

def dejanStankovic(request):
    
    
    context = {
        

    }
    
    return render(request, 'index/dejan_stankovic.html', context)

def gallery(request):
    
    
    context = {
        

    }
    
    return render(request, 'index/gallery.html', context)


def aboutUs(request):
    
    
    context = {
        

    }
    
    return render(request, 'index/about_us.html', context)


def privacyPolicy(request):
    
    
    context = {
        

    }
    
    return render(request, 'index/privacy_policy.html', context)


def videoEducation(request):
    
    
    context = {
        

    }
    
    return render(request, 'index/video_education.html', context)


def blog(request):
    
    
    context = {
        

    }
    
    return render(request, 'index/blog.html', context)


def oprostajnoPismo(request):
    
    
    context = {
        

    }
    
    return render(request, 'index/oprostajno_pismo.html', context)

serbian_ver/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse

def index(request):
    
    
    context = {
        

    }
    
    return render(request, 'serbian/index/index.html', context)

def contact(request):
    
    
    context = {
        

    }
    
    return render(request, 'serbian/index/contact.html', context)


def treatmentGamblers(request):
    
    
    context = {
        

    }
    
    return render(request, 'serbian/index/treatment_of_gamblers.html', context)


def weaningProgram(request):
    
    
    context = {
        

    }
    
    return render(request, 'serbian/index/family_and_gambler.html', context)


def gamblingProblem(request):
    
    
    context = {
        

    }
    
    return render(request, 'serbian/index/gambling_problem_scene.html', context)


def gamblingAddiction(request):
    
    
    context = {
        

    }
    
    return render(request, 'serbian/index/gambling_addiction.html', context)

def pathologicalGambling(request):
    
    
    context = {
        

    }
    
    return render(request, 'serbian/index/pathological_gambling.html', context)


def dealingGambling(request):
    
    
    context = {
        

    }
    
    return render(request, 'serbian/index/dealing_with_gambling_problem.html', context)

templates/index/about_us.html
{% extends "core/base_xherc.html" %} {% block title %} About Us Herctime MK {% endblock title %} {% load static %} {% block content %}

<style>
    .banner-next::after {
        content: '';
        position: absolute;
        left: 50%;
        top: 50%;
        min-width: 100%;
        height: auto;
        min-height: 100%;
        width: auto;
        width: 100%;
        height: 100%;
        transform: translateY(-50%)translateX(-50%);
        object-fit: cover;
        background-image: url(https://www.rehabguide.co.uk/wp-content/uploads/2019/10/Gambling-1200x900.jpg);
        background-size: 100%;
        background-repeat: no-repeat;
        z-index: 0;
        filter: sepia(90%);
    }
    
    .htime10-content {
        z-index: 1;
        position: relative;
        padding: 3rem;
        background-color: rgba(201, 199, 200, .8);
    }
</style>





<section id="content-next-001">
    <div class="content-next mb-10">
        <nav aria-label="breadcrumb" class="my-5">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a class="dark-primary fw-600" href="/">Почетна</a></li>
                <li class="breadcrumb-item deep-carmine" aria-current="page">за нас</li>
            </ol>
        </nav>


        <div style="background-color: antiquewhite;" class="position-relative ">
            <div class="banner-next">
                <div class="row">
                    <!-- min-width:992px -->

                    {% include 'plugin/herc_program_banner.html' %}

                </div>
            </div>
        </div>

        <div class="row">

            <!-- max-width:992px  Banner Small -->
            <div class="d-none992min">
                <div class="row g-0">
                    <div class="row g-0">

                        <img class="img-fluid" src="https://www.rehabguide.co.uk/wp-content/uploads/2019/10/Gambling-1200x900.jpg" alt="">
                        <div class="deep-carmine-bg p-4">
                            <div class="text-center mb-4">
                                <h2 class="mb-4 white-primary" style="font-size: calc(1.125rem + .9vw);">Програма за третман на ХЕРЦ за патолошки коцкари</h2>
                                <p class="white-primary"> Третманот на коцкарите според ХЕРЦ методот е резултат на работа со луѓе кои се зависни од патолошко коцкање и членови на нивните семејства.</p>

                            </div>
                            <div class="d-block text-center">
                                <div>
                                    <button data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@getbootstrap" style="opacity: 1;" class="mb-3 
                                                     ht-next-link-white">+389 75 660 840</button>
                                </div>
                                <div class="mb-3">
                                    <a href="{% url 'index:consultation' %}" class="ht-next-link-white">Закажете консултација</a>
                                </div>
                            </div>

                        </div>




                    </div>




                </div>

            </div>

        </div>
        <div class="container mt-5 p-0">
            <div class="row g-0">
                <div class="col-xl-8 col-lg-7 main-content">

                    <h1 class="deep-carmine">Ние го решавеме проблемот!</h1>
                    <p>
                        „HERCTIME“, центар за одвикнување од патолошкото коцкање во Скопје, е дел од компанијата „Herc Time“ во Нови Сад, која веќе дваесет години успешно се справува со проблемот на патолошкиот коцкање. Програмата се базира на едукација насочена кон стекнување
                        нови знаења и вештини со цел да се надминат импулсите и исклучувањето со коцкарскиот модел на функционирање.
                    </p>


                    <p>
                        Едукацијата се врши индивидуално, без лекови, со комбинирање на поддршката од тим од експерти, психолози и личната програма на <a href="{% url 'index:dejan_stankovic' %}">Дејан Станковиќ</a> . Откажувањето од коцкањето е сериозен
                        процес и бара сериозен пристап. Третманот на коцкарите е можен и многу успешен со нашата програма. Нашата програма за обука се покажа како најефикасна и со клиенти од регионот и со клиенти од цела Европа. Ви нудиме едноставно решение
                        кое е брзо и ефикасно. Со наша помош и ваша одлука, навистина го имате вистинскиот начин да престанете да се коцкате.
                    </p>

                    <h2>Книгите на Дејан Станковиќ</h2>
                    <hr>
                    <p>
                        Откажувањето од коцкањето е сериозен процес и бара сериозен пристап. Лекувањето на коцкарите е можно и многу успешно во нашиот центар. Ви нудиме уникатно решение, кое е брзо и ефикасно. Со наша помош и ваша одлука, навистина го имате вистинскиот начин
                        да престанете да се коцкате. Ако се сомневате дека некој член од вашето семејство има проблем со коцкањето, можете да прочитате една од нашите претходни написи за знаците на патолошкото коцкање кај член на семејството. Подетални
                        информации за проблемот со коцкањето можете да најдете на нашата веб-страница
                    </p>
                    <div class="row">
                        <div class="col-lg-6 mb-3">
                            <img class="img-fluid" style="max-height: 400px;object-fit: cover;" src="https://flesbeograd.rs/wp-content/uploads/2022/05/clipboard_image_ccaa379aaf87927a.jpg" alt="Ulog">
                            <p class="text-center">
                                <strong>
                                    Knjiga "Ulog"
                                </strong>
                            </p>
                        </div>
                        <div class="col-lg-6 mb-3">
                            <img src="https://flesbeograd.rs/wp-content/uploads/2022/05/clipboard_image_847cc0c1672fa776.jpg" alt="Zbogom kockanje" class="img-fluid" style="max-height: 400px;object-fit: cover;">
                            <p class="text-center">
                                <strong>
                                    Knjiga "Zbogom kockanje"
                                </strong>
                            </p>
                        </div>
                        <div class="col-lg-6 mb-3">
                            <img src="https://flesbeograd.rs/wp-content/uploads/2022/05/clipboard_image_46e150eb96cb31d4.jpg" alt="Zbogom kockanje" class="img-fluid" style="max-height: 400px;object-fit: cover;">
                            <p class="text-center">
                                <strong>
                                    Knjiga "Patološko kockanje, uzroci i posledice"
                                </strong>
                            </p>
                        </div>
                        <div class="col-lg-6 mb-3">
                            <img src="https://www.ulog.ba/assets/images/knjiga.webp" alt="Zbogom kockanje" class="img-fluid" style="max-height: 400px;object-fit: cover;">
                            <p class="text-center">
                                <strong>
                                    Knjiga "Oproštajno pismo"
                                </strong>
                            </p>
                        </div>


                    </div>

                </div>
                {% include 'plugin/right_bar.html' %}

            </div>
        </div>


    </div>


</section>

<!--  -->

{% endblock %}

templates/index/index.html
{% extends "core/base_xherc.html" %} {% block title %} Index {% endblock title %} {% load static %} {% block content %}

<style>
    .bg-about {
        background-color: #020d1f;
        background-color: #0b0f19;
        background-color: #0b0e1d;
        /* background-color: #171b25; */
        z-index: 0;
    }
    
    .bg-base {
        background-image: url('../../static/img/bg-about-1.2.jpg');
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }
    
    .layer-video::after {
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: var(--dark-blue-black);
        opacity: .25;
        z-index: -1;
    }
    
    .elementYt::before {
        content: '';
        background-position: 0% 50%;
        background-size: cover;
        background-repeat: no-repeat;
        /* background-image: url("https://silicon.createx.studio/assets/img/landing/digital-agency/hero-bg.svg");
        background-image: url("../../static/img/hero-bg.png");
        background-image: url("../../static/img/bg.jpg"); */
        position: absolute;
        top: 0px;
        left: 0px;
        width: 100%;
        height: 100%;
        overflow: hidden;
        pointer-events: none;
        transform-style: preserve-3d;
        backface-visibility: hidden;
        margin-top: -74.65px;
        transform: translate3d(0px, 74.65px, 0px);
        /* z-index: -1; */
        background-color: #020d1f;
        /* opacity: .10; */
        /* background: radial-gradient(ellipse at top, #cac0ca, transparent), radial-gradient(ellipse at bottom, #c9c7c8, transparent); */
        /* height: 720px; */
    }
</style>
<div class="">
    {% include 'plugin/banner.html' %}
</div>

<!--  -->
{% include 'plugin/herctime_002.html' %}
<!--  -->
{% include 'plugin/herctime_003.html' %}
<!--  -->
{% include 'plugin/herctime_004.html' %}
<!--  -->

{% include 'plugin/parallax.html' %}
<!--  -->
{% include 'plugin/herctime_005.html' %}
<!--  -->

<!--  -->

{% endblock %}

templates/plugin/herctime_002.html
{% load static %}

<section id="herctime-002" style="overflow: hidden;">

    <div class="position-relative bg-about bg-about">

        <div class="pt-5 px-5 d-flex align-items-baseline position-relative">
            <h6 style="position: absolute;top: 0;left: 2.5%;" class="me-4 section-numb">01</h6>
            <div class="ps-7x">
                <h1 class="neon-silver f-200 mb-4">За нас</h1>
                <!-- <h3 class="neon-silver mb-5 fw-800">Прв чекор во решавањето на проблемот со коцкање</h3> -->
            </div>
        </div>
        <div class="content-hub" style="padding: 0 12px;">
            <div class="row">
                <div class="col-lg-6">

                    <div class="py-8">
                        <div class="position-relative layer-video">
                            <video controls="" autoplay="" muted="" playsinline="" loop="" class="center mb-4 ratio ratio-4x3" style="z-index: -1;">
                                <source src="{% static 'img/herctime.mp4' %}" type="video/mp4">
                                <p>Sorry, your broswer doesn't support embedded videos.</p>
                            </video>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="w-100 mt-10 px-7 py-5 impact-d" data-aos="fade-up" data-aos-duration="3000">
                        <!-- <p class="pb-4" style="color:var(--primary-white);">За нас</p> -->
                        <h2 style="line-height: 1;margin-bottom: 1rem;">
                            <span style="color:var(--deep-carmine)"> "Herctime"</span> <span style="font-weight: 700;">центар за одвикнување од патолошко коцкање</span></h2>
                        <!-- <h4 style="color:var(--primary-white);font-size: 4rem;font-weight: 600;">centar za odvikavanje od patološkog kockanja</h4> -->
                        <h5 class="fw-200" style="color:var(--primary-white); ">Центарот за одвикнувањево во Скопје, е дел од фирмата "Herc Time" во Нови Сад, која веќе 10 години успешно работи со решавање на проблеми со патолошко коцкање
                        </h5>
                        <div class="mt-5">
                            <a href="{% url 'index:about_us' %}" class="hRgTcm " style="background-color: var(--deep-carmine);color:var(--primary-white)">Прочитај
                            повеќе</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/plugin/video_edit_banner_sm.html
<!-- max-width:992px -->
<div class="d-none992min">
    <div class="row g-0">

        <img class="img-fluid" src="{% static 'img/family-and-gembler.webp' %}" alt="">
        <div class="deep-carmine-bg p-4">
            <div class="text-center mb-4">
                <h2 class="mb-4 white-primary" style="font-size: calc(1.125rem + .9vw);">Програма за третман на ХЕРЦ за патолошки коцкари</h2>
                <p class="white-primary"> Третманот на коцкарите според ХЕРЦ методот е резултат на работа со луѓе кои се зависни од патолошко коцкање и членови на нивните семејства.</p>

            </div>
            <div class="d-block text-center">
                <div>
                    <button data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@getbootstrap" style="opacity: 1;" class="mb-3 
                                     ht-next-link-white">+389 75 660 840</button>
                </div>
                <div class="mb-3">
                    <a href="{% url 'index:consultation' %}" class="ht-next-link-white">Закажете консултација</a>
                </div>
            </div>

        </div>




    </div>

</div>

templates/serbian/plugin/navbar_bUp.html
 {% load static %}


<style>
    .net-svg {
        fill: #2b2a45;
        width: 25px;
        height: auto;
    }
    
    .s-net-cont {
        margin-right: .5rem;
    }
    
    .hRgTcm {
        background-color: transparent;
        color: #2b2a45;
        letter-spacing: 0.1rem;
        font-weight: 600;
        text-transform: uppercase;
        border: 2px solid #a8273e;
        border-radius: 50px;
        padding: 15px 25px;
        font-size: 12px;
        pointer-events: inherit;
        cursor: pointer;
        transition: background-color 0.25s ease-in-out 0s, color 0.25s ease-in-out 0s;
        z-index: 5;
    }
</style>
<section id="herctime-001">

    <div class="info-header p-3 header" style="">
        <div class="px-5 d-flex justify-content-between align-items-center">
            <div class="d-block">
                <div>
                    <img src="{% static 'img/logo-original-mk1.png' %}" style="width: 150px;height: auto;" alt="Herctime">
                </div>
                <span style="font-size: .755rem;font-weight: 500; padding: 0 .25rem; color: #2b2a45;border-radius: .15rem; text-transform: uppercase;">Центар за едукација и одвикнување од коцка</span>
            </div>



            <div class="d-flex bg-grunge--mask align-items-center">
                <div class="div s-net-cont">
                    <svg xmlns="http://www.w3.org/2000/svg" class="net-svg bi bi-facebook" viewBox="0 0 16 16">
                        <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"></path>
                      </svg>
                </div>

                <div class="div s-net-cont">
                    <a href="#">
                        <svg xmlns="http://www.w3.org/2000/svg" class="net-svg bi bi-youtube" viewBox="0 0 16 16">
                            <path d="M8.051 1.999h.089c.822.003 4.987.033 6.11.335a2.01 2.01 0 0 1 1.415 1.42c.101.38.172.883.22 1.402l.01.104.022.26.008.104c.065.914.073 1.77.074 1.957v.075c-.001.194-.01 1.108-.082 2.06l-.008.105-.009.104c-.05.572-.124 1.14-.235 1.558a2.007 2.007 0 0 1-1.415 1.42c-1.16.312-5.569.334-6.18.335h-.142c-.309 0-1.587-.006-2.927-.052l-.17-.006-.087-.004-.171-.007-.171-.007c-1.11-.049-2.167-.128-2.654-.26a2.007 2.007 0 0 1-1.415-1.419c-.111-.417-.185-.986-.235-1.558L.09 9.82l-.008-.104A31.4 31.4 0 0 1 0 7.68v-.123c.002-.215.01-.958.064-1.778l.007-.103.003-.052.008-.104.022-.26.01-.104c.048-.519.119-1.023.22-1.402a2.007 2.007 0 0 1 1.415-1.42c.487-.13 1.544-.21 2.654-.26l.17-.007.172-.006.086-.003.171-.007A99.788 99.788 0 0 1 7.858 2h.193zM6.4 5.209v4.818l4.157-2.408L6.4 5.209z"/>
                          </svg>
                    </a>
                </div>

                <div class="div s-net-cont">
                    <svg xmlns="http://www.w3.org/2000/svg" class="net-svg bi bi-twitter" viewBox="0 0 16 16">
                        <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"></path>
                      </svg>
                </div>



                <div class="dropdown">

                    <button class="btn btn-secondary dropdown-toggle d-flex align-items-center" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-globe-europe-africa" viewBox="0 0 16 16">
                            <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0ZM3.668 2.501l-.288.646a.847.847 0 0 0 1.479.815l.245-.368a.809.809 0 0 1 1.034-.275.809.809 0 0 0 .724 0l.261-.13a1 1 0 0 1 .775-.05l.984.34c.078.028.16.044.243.054.784.093.855.377.694.801-.155.41-.616.617-1.035.487l-.01-.003C8.274 4.663 7.748 4.5 6 4.5 4.8 4.5 3.5 5.62 3.5 7c0 1.96.826 2.166 1.696 2.382.46.115.935.233 1.304.618.449.467.393 1.181.339 1.877C6.755 12.96 6.674 14 8.5 14c1.75 0 3-3.5 3-4.5 0-.262.208-.468.444-.7.396-.392.87-.86.556-1.8-.097-.291-.396-.568-.641-.756-.174-.133-.207-.396-.052-.551a.333.333 0 0 1 .42-.042l1.085.724c.11.072.255.058.348-.035.15-.15.415-.083.489.117.16.43.445 1.05.849 1.357L15 8A7 7 0 1 1 3.668 2.501Z"/>
                          </svg><div class="ms-2"> Macedonian</div>
                    </button>
                    <ul class="dropdown-menu shadow-lg">
                        <li><a class="dropdown-item" href="#">Serbian</a></li>
                        <li><a class="dropdown-item" href="#">English</a></li>

                    </ul>
                </div>

                <button data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@getbootstrap" style="opacity: 1;" class="StartButton-sc-1wk0cgj-2 hRgTcm">Закажете консултација</button>
            </div>

        </div>
    </div>

    <nav id="navigation" class="navbar navbar-expand-lg bg-body-tertiary bg-red-carmine sticky-top">
        <div class="content-herc">
            <div class="dislpay-flex-001">
                <a class="navbar-brand d-none992min" href="#">Herctime.</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
            </div>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Почетна</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link dislpay-flex-001" href="#">
                            <!-- <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-circle-fill" viewBox="0 0 16 16">
                                <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
                              </svg> -->
                            <span> За нас</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Програм за одвикнување </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Видео едукација </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Романи
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'index:romani' %}">Greensoks 1</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>


                    <li class="nav-item">
                        <a class="nav-link" href="#">Блог </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'index:contact' %}" class="nav-link" style="border-right:0">
                            <!-- <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone-inbound-fill" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511zM15.854.146a.5.5 0 0 1 0 .708L11.707 5H14.5a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5v-4a.5.5 0 0 1 1 0v2.793L15.146.146a.5.5 0 0 1 .708 0z"/>
                              </svg> -->
                            <span> Контакт</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

</section>


<style>
    /* .content {
        padding: 16px;
    } */
    
    .sticky {
        position: fixed;
        top: 0;
        width: 100%;
        transition: ease 0.4s;
    }
    /* .sticky+.content {
        padding-top: 60px;
    } */
</style>




<script>
    // fixed navbar
    window.onscroll = function() {
        myFunction()
    };

    var navigation = document.getElementById("navigation");
    var sticky = navigation.offsetTop;

    function myFunction() {
        if (window.pageYOffset >= sticky) {
            navigation.classList.add("sticky")
        } else {
            navigation.classList.remove("sticky");
        }
    }
</script>